<?php

/**
 * @file
 * A module that acts as a central point for the redirections on the site.
 */

function redirector_entity_info() {
  $return = array(
    'redirector_rule' => array(
      'label' => t('Redirector Rule'),
      'controller class' => 'RedirectorRuleEntityController',
      'base table' => 'redirector_rules',
      'entity keys' => array(
        'id' => 'rid',
        'label' => 'title',
      ),
    ),
  );
  return $return;
}

/**
 * Implements hook_permission().
 */
function redirector_permission() {
  return array(
    'skip redirector redirects' => array(
      'title' => t('Skip Redirects'),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function redirector_theme() {
  return array(
    'redirector_current_rules_form' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Implements hook_init().
 */
function redirector_init() {
  // Skip any redirect if called from the cli.
  if (drupal_is_cli()) {
    return;
  }
  // Skip the redirect if the current user is allowed to do so.
  if (user_access('skip redirector redirects')) {
    return;
  }
  // @todo: this should be improved as much as possible!
  // @todo: we should split this in more functions if we will need this
  // functionality in other places.
  $rules = redirector_rule_load_multiple();
  $active_components = redirector_get_active_components();
  $rule_controller = entity_get_controller('redirector_rule');
  $redirect_rule = NULL;
  foreach ($rules as &$rule) {
    // The $complete_match will check if the current request matches entirerly
    // a rule, which is if it matches the destination and source parts merged
    // togheter. If a complete match happens, then no redirect should be made.
    $complete_match = TRUE;
    // The $source_match will check if the current request matches the source
    // part of the rule. This will be used to determine which redirect rule to
    // apply when doing the redirect.
    $source_match = TRUE;
    foreach ($active_components as $component_key => $component) {
      $component_match = $rule_controller->matchComponent($rule, $component, array('dest', 'source'));
      if (!$component_match) {
        $complete_match = FALSE;
      }
      if (empty($redirect_rule) && !empty($source_match)) {
        $source_component_match = $rule_controller->matchComponent($rule, $component, array('source'));
        if (!$source_component_match) {
          $source_match = FALSE;
        }
      }
      // If this rule does already not matches the source part nor the complete
      // we just continue to the next rule.
      if (!$source_match && !$complete_match) {
        continue 2;
      }
    }
    // No redirect if we found a complete match. This means that the user is on
    // a valid page.
    if (!empty($complete_match)) {
      return;
    }
    // We found the first redirect rule that matches the request.
    if (!empty($source_match) && empty($redirect_rule)) {
      $redirect_rule = $rule;
    }
  }

  if (!empty($redirect_rule)) {
    redirector_rule_redirect($redirect_rule, $active_components);
  }
}

/**
 * Makes a redirect based on the rule.
 *
 * @param stdClass $redirect_rule
 *  The redirect rule to check.
 *
 * @param array $components
 *  An array of components to use for the redirect.
 */
function redirector_rule_redirect($redirect_rule, $components = array()) {
  $url = $_GET['q'];
  $options['query'] = drupal_get_query_parameters();;
  // Unset the destination from the parameter to make sure we will not be
  // redirected to it by the drupal_goto().
  if (isset($_GET['destination'])) {
    unset($_GET['destination']);
  }
  if (empty($components)) {
    $components = redirector_get_active_components();
  }
  $rule_controller = entity_get_controller('redirector_rule');
  // @todo: should we show the debug based on a setting?
  $debug_output = array();
  foreach ($components as $component) {
    drupal_add_http_header('X-Redirector-Current-' . str_replace(' ', '-', $component->getTitle()), implode(',', $component->getCurrentValue()));
    $component_values = $rule_controller->getComponentValues($redirect_rule, $component);
    $debug_output[] = $component->summary($component_values);
    $rule_controller->prepareComponentRedirect($redirect_rule, $component, $url, $options);
  }
  // For the site homepage, just reset the URL.
  if (variable_get('site_frontpage', 'node') == $url) {
    $url = '';
  }
  drupal_add_http_header('X-Redirector-Rule', $redirect_rule->title);
  drupal_add_http_header('X-Redirector-Rule-Condition', implode(' && ', $debug_output));
  drupal_goto($url, $options);
}

/**
 * Implements hook_menu().
 */
function redirector_menu() {
  $path = redirector_get_admin_path();
  $items[$path] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Redirector',
    // Maybe we should create another permission.
    'access arguments' => array('administer site'),
    'page callback' => 'redirector_admin_rules_page',
    'file' => 'redirector.admin.inc',
  );
  $items[$path. '/components'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Components',
    'access arguments' => array('administer site'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('redirector_admin_components_form'),
    'file' => 'redirector.admin.inc',
  );
  $items[$path . '/rules'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'title' => 'Rules',
    'weight' => -5,
  );
  $items[$path . '/rules/edit/%redirector_rule'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Edit rule',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('redirector_admin_add_edit_rule_form', 6),
    'access arguments' => array('administer site'),
    'file' => 'redirector.admin.inc',
  );
  $items[$path . '/rules/delete/%redirector_rule'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Delete rule',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('redirector_admin_delete_rule_confirm', 6),
    'access arguments' => array('administer site'),
    'file' => 'redirector.admin.inc',
  );
  return $items;
}

/**
 * Loads a single redirector rule by its id.
 *
 * @param int $rid
 *  The rule id.
 */
function redirector_rule_load($rid) {
  return entity_load_single('redirector_rule', $rid);
}

/**
 * Loads all the rules.
 */
function redirector_rule_load_multiple($conditions = array()) {
  // For the moment we use the entity_load() but we may need a custom query in
  // the future. Maybe one where we directly sort the results.
  $rules = entity_load('redirector_rule', FALSE, $conditions);
  uasort($rules, '_redirector_sort_callback');
  return $rules;
}

/**
 * Sort callback for a set of redirector objects.
 */
function _redirector_sort_callback($a, $b) {
  return $a->weight < $b->weight ? -1 : 1;
}

/**
 * Sort callback for a set of components, where they are structured as arrays..
 */
function _redirector_sort_callback_array($a, $b) {
  $a += array('weight' => 0);
  $b += array('weight' => 0);
  return $a['weight'] < $b['weight'] ? -1 : 1;
}

/**
 * Helper function to return the link to edit a rule.
 *
 * @param int $rid
 *  The rule id.
 */
function redirector_edit_rule_link($rid) {
  return 'admin/config/system/redirector/rules/edit/' . $rid;
}

/**
 * Helper function to return the link to edit a rule.
 *
 * @param int $rid
 *  The rule id.
 */
function redirector_delete_rule_link($rid) {
  return 'admin/config/system/redirector/rules/delete/' . $rid;
}

/**
 * Helper function to return the admin path.
 */
function redirector_get_admin_path() {
  return 'admin/config/system/redirector';
}

/**
 * Helper function to return the possible parts of a rule.
 */
function redirector_rule_parts() {
  return array('source' => array('title' => t('Source'), 'allow_multiple' => TRUE, 'allow_negate' => TRUE),
               'dest' => array('title' => t('Destination')));
}

/**
 * Returns an array with all the available components.
 */
function redirector_get_all_components() {
  // @todo: maybe cache this if used intensively. And if cached, the cache key
  // must contain the langauge, because we use t() in the title of the
  // components.
  $components = &drupal_static(__FUNCTION__);
  if (is_null($components)) {
    $components = module_invoke_all('redirector_components');
    uasort($components, '_redirector_sort_callback_array');
    // @todo: invoke an alter if needed.
  }
  return $components;
}

/**
 * Returns an array with the active components.
 *
 * @return array RedirectorComponent
 */
function redirector_get_active_components() {
  $components = variable_get('redirector_components', array());
  if (!empty($components)) {
    foreach ($components as $key => $name) {
      $components[$key] = redirector_get_component($key);
    }
    uasort($components, '_redirector_sort_callback');
  }
  return $components;
}

/**
 * Creates a component object based on a component id.
 *
 * @param string $component_id
 *  The id of the component.
 *
 * @return RedirectorComponent
 */
function redirector_get_component($component_id) {
  $components = &drupal_static(__FUNCTION__);
  $all_components = redirector_get_all_components();
  if (empty($components[$component_id]) && class_exists($all_components[$component_id]['class'])) {
    $components[$component_id] = new $all_components[$component_id]['class']($all_components[$component_id]);
  }
  return $components[$component_id];
}

/**
 * Implements hook_redirector_components().
 *
 * @todo: document this hook.
 */
function redirector_redirector_components() {
  return array(
    'language' => array(
      'class' => 'RedirectorComponentLanguage',
    ),
    'country' => array(
      'class' => 'RedirectorComponentCountry',
      'weight' => 10,
    ),
  );
}
